version: '3.7'
name: microservices

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - ${MINIO_PORT}:9000
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:${MINIO_DATA_DIR}
    command: server --console-address ":9001" ${MINIO_DATA_DIR}
    restart: always
    
volumes:
  minio-data: